'use client';
import {useEffect,useState, type FormEvent} from 'react';
import Link from 'next/link';
import {ArrowRight,CalendarDays,Check,Info,Plus,Trash2} from 'lucide-react';
import {events,products,defaultSettings,money,dateLabel} from '@/lib/data';
import {toast} from 'sonner';

type Section='evento'|'lotes'|'camisetas'|'kit'|'lojas'|'produtos'|'eventos'|'parceiros';
type Draft={name:string;date:string;time:string;place:string;description:string;lotEnd:string;lotQuantity:number;prices:Record<string,number>;stock:Record<string,number>;kit:string[];storeEnabled:boolean;offers:{name:string;price:number;later:number;stock:number}[]};
const initial:Draft={name:events[0].name,date:events[0].date,time:events[0].time,place:events[0].place,description:events[0].description,lotEnd:defaultSettings.lotEnd,lotQuantity:defaultSettings.lotQuantity,prices:Object.fromEntries([5,7,10,15,21,42].map(k=>[k,100+(k>=42?90:k>=21?40:k>=15?30:k>=10?20:k>=7?10:0)])),stock:Object.fromEntries([5,7,10,15,21,42].flatMap(k=>['PP','P','M','G','GG','XGG'].map(s=>[`${k}-${s}`,s==='XGG'?0:40]))),kit:['Camiseta da modalidade','Número de peito','Chip de cronometragem','Medalha após a conclusão','Sacochila do evento'],storeEnabled:true,offers:products.map(p=>({name:p.name,price:p.price,later:p.later,stock:p.stock}))};
const notice=<div className="alert-note"><Info size={18}/>Rascunho de demonstração salvo apenas neste navegador. A vitrine e a compra continuam com os eventos ilustrativos.</div>;
export default function ManagementPage({section}:{section:Section}){
 const [draft,setDraft]=useState<Draft>(initial),[newKit,setNewKit]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{try{const saved=sessionStorage.getItem('vibe-management-demo');if(saved)setDraft({...initial,...JSON.parse(saved)})}catch{}setReady(true)},[]);
 function save(e:FormEvent){e.preventDefault();try{sessionStorage.setItem('vibe-management-demo',JSON.stringify(draft));toast.success('Rascunho de demonstração salvo neste navegador.')}catch{toast.error('Não foi possível guardar o rascunho neste navegador.')}}
 const set=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(d=>({...d,[key]:value}));
 if(!ready)return <section className="panel">Preparando esta tela…</section>;
 if(section==='eventos')return <div className="stack"><section className="panel"><h3>Eventos da plataforma</h3><p className="muted">Abra o painel do organizador ou a página que o atleta verá.</p><div className="stack" style={{marginTop:20}}>{events.map(ev=><div className="receipt" key={ev.id}><div><strong>{ev.name}</strong><p className="small muted">{dateLabel(ev.date)} · {ev.city} · {ev.distances.join(', ')} km</p></div><div className="row"><Link className="btn outline" href={'/evento/'+ev.id}>Ver vitrine</Link><Link className="btn primary" href="/gestao">Gerenciar <ArrowRight size={15}/></Link></div></div>)}</div></section>{notice}</div>;
 if(section==='parceiros')return <div className="stack"><section className="panel"><h3>Organizadores e lojas</h3><p className="muted">Fluxo de autorização e acesso dos parceiros.</p><div className="screens-grid" style={{marginTop:22}}><Link className="screen-card" href="/admin/equipe"><span><strong>Convites e acessos</strong><small>Cadastre organizadores e lojistas para liberar o acesso.</small></span><ArrowRight size={18}/></Link><Link className="screen-card" href="/gestao/lojas"><span><strong>Lojas no evento</strong><small>Veja como a participação é autorizada pelo organizador.</small></span><ArrowRight size={18}/></Link><Link className="screen-card" href="/loja"><span><strong>Área da lojinha</strong><small>Confira ofertas, pedidos e retiradas no balcão.</small></span><ArrowRight size={18}/></Link></div></section>{notice}</div>;
 if(section==='lojas')return <div className="stack"><section className="panel"><h3>Lojas parceiras neste evento</h3><p className="muted">Autorize a participação para isentar o setup de {money(defaultSettings.setup)}.</p><label className="row" style={{margin:'24px 0',fontSize:16}}><input type="checkbox" checked={draft.storeEnabled} onChange={e=>set('storeEnabled',e.target.checked)}/>Permitir ofertas das lojas na compra</label><div className="receipt"><div><strong>Ponto do Atleta</strong><p className="small muted">Rua das Palmeiras, 120 · Centro · aluguel de {money(defaultSettings.rent)} por evento</p></div><Link className="btn outline" href="/loja">Ver loja <ArrowRight size={15}/></Link></div></section><form onSubmit={save}>{notice}<button className="btn primary" style={{marginTop:20}}>Salvar rascunho</button></form></div>;
 if(section==='evento')return <form className="stack" onSubmit={save}><section className="panel"><h3>Dados da corrida</h3><p className="muted">Visualize como o cadastro do evento será preenchido pelo organizador.</p><div className="form-grid" style={{marginTop:22}}><label className="field">Nome do evento<input required value={draft.name} onChange={e=>set('name',e.target.value)}/></label><label className="field">Data da prova<input type="date" required value={draft.date} onChange={e=>set('date',e.target.value)}/></label><label className="field">Horário da largada<input type="time" required value={draft.time} onChange={e=>set('time',e.target.value)}/></label><label className="field">Local da largada<input required value={draft.place} onChange={e=>set('place',e.target.value)}/></label><label className="field wide">Apresentação do evento<textarea value={draft.description} onChange={e=>set('description',e.target.value)}/></label></div></section><div className="row" style={{flexWrap:'wrap'}}><Link href="/gestao/lotes" className="btn outline">Próximo: lotes e distâncias <ArrowRight size={15}/></Link><Link href="/evento/orla" className="btn outline">Ver página do atleta</Link></div>{notice}<button className="btn primary">Salvar rascunho</button></form>;
 if(section==='lotes')return <form className="stack" onSubmit={save}><section className="panel"><h3>1º lote · distâncias e preços</h3><p className="muted">O lote seguinte pode começar quando a quantidade se esgotar ou chegar a data definida. Altere a data para simular uma prorrogação.</p><div className="form-grid" style={{margin:'22px 0'}}><label className="field">Data de encerramento<input type="date" required value={draft.lotEnd} onChange={e=>set('lotEnd',e.target.value)}/></label><label className="field">Limite de inscrições<input type="number" min="1" required value={draft.lotQuantity} onChange={e=>set('lotQuantity',Number(e.target.value))}/></label></div><div className="table-scroll"><table className="demo-table"><thead><tr><th>Distância</th><th>Preço da inscrição</th><th>Próxima etapa</th></tr></thead><tbody>{[5,7,10,15,21,42].map(k=><tr key={k}><td><strong>{k} km</strong></td><td><label className="field">Preço em R$<input type="number" min="0" step="0.01" value={draft.prices[k]} onChange={e=>set('prices',{...draft.prices,[k]:Number(e.target.value)})}/></label></td><td><Link href="/gestao/camisetas">Estoque de camiseta <ArrowRight size={14}/></Link></td></tr>)}</tbody></table></div></section>{notice}<button className="btn primary">Salvar rascunho</button></form>;
 if(section==='camisetas')return <form className="stack" onSubmit={save}><section className="panel"><h3>Estoque de camisetas por distância</h3><p className="muted">Cada distância pode ter uma camiseta própria. Zero significa tamanho esgotado. Durante o pagamento a peça fica reservada; após a compra, pode ser retirada até 30 dias depois da prova.</p><div className="table-scroll"><table className="demo-table"><thead><tr><th>Prova</th>{['PP','P','M','G','GG','XGG'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{[5,7,10,15,21,42].map(k=><tr key={k}><th>{k} km</th>{['PP','P','M','G','GG','XGG'].map(s=><td key={s}><input aria-label={`${k} km tamanho ${s}`} type="number" min="0" value={draft.stock[`${k}-${s}`]??0} onChange={e=>set('stock',{...draft.stock,[`${k}-${s}`]:Number(e.target.value)})}/></td>)}</tr>)}</tbody></table></div></section>{notice}<button className="btn primary">Salvar rascunho</button></form>;
 if(section==='kit')return <form className="stack" onSubmit={save}><section className="panel"><h3>Itens do kit da corrida</h3><p className="muted">O kit normalmente é o mesmo para todas as distâncias. A camiseta é controlada separadamente por modalidade e tamanho.</p><div className="stack" style={{marginTop:20}}>{draft.kit.map((item,i)=><div className="receipt" key={i}><span><Check size={16} style={{display:'inline',marginRight:10}}/>{item}</span><button type="button" className="icon-btn" aria-label={'Remover '+item} onClick={()=>set('kit',draft.kit.filter((_,n)=>n!==i))}><Trash2 size={17}/></button></div>)}</div><div className="row" style={{marginTop:20}}><input aria-label="Novo item do kit" placeholder="Novo item do kit" value={newKit} onChange={e=>setNewKit(e.target.value)}/><button type="button" className="btn outline" onClick={()=>{if(newKit.trim()){set('kit',[...draft.kit,newKit.trim()]);setNewKit('')}}}><Plus size={16}/>Adicionar</button></div></section>{notice}<button className="btn primary">Salvar rascunho</button></form>;
 return <form className="stack" onSubmit={save}><section className="panel"><h3>Produtos e ofertas da loja</h3><p className="muted">Defina o preço na inscrição, o preço posterior e o estoque. A oferta antecipada aparece durante a compra.</p><div className="stack" style={{marginTop:20}}>{draft.offers.map((offer,i)=><div className="panel" key={i} style={{background:'#f8fbfa'}}><div className="row between"><h3>Produto {i+1}</h3><button type="button" className="icon-btn" aria-label={'Remover produto '+(i+1)} onClick={()=>set('offers',draft.offers.filter((_,n)=>n!==i))}><Trash2 size={17}/></button></div><div className="form-grid"><label className="field wide">Nome<input required value={offer.name} onChange={e=>set('offers',draft.offers.map((p,n)=>n===i?{...p,name:e.target.value}:p))}/></label>{([['price','Preço junto à inscrição'],['later','Preço posterior'],['stock','Estoque']] as const).map(([key,label])=><label className="field" key={key}>{label}<input type="number" min="0" step={key==='stock'?'1':'0.01'} value={offer[key]} onChange={e=>set('offers',draft.offers.map((p,n)=>n===i?{...p,[key]:Number(e.target.value)}:p))}/></label>)}</div></div>)}</div><button type="button" className="btn outline" style={{marginTop:20}} onClick={()=>set('offers',[...draft.offers,{name:'',price:0,later:0,stock:0}])}><Plus size={16}/>Adicionar produto</button></section><Link href="/loja/configuracoes" className="btn outline">Endereço e horários de retirada <ArrowRight size={15}/></Link>{notice}<button className="btn primary">Salvar rascunho</button></form>;
}
