import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {initialWorkspace,events,products,racePrice,feeFor,Workspace} from '@/lib/data';
export const dynamic='force-dynamic';
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function who(){const u=await getChatGPTUser();return u?.userId}
export async function GET(){const owner=await who();if(!owner)return reply({error:'Entre na prévia privada para salvar suas alterações.',preview:true},401);try{const row=await env.DB!.prepare('SELECT data,revision FROM viva_workspaces WHERE owner=?').bind(owner).first<{data:string;revision:number}>();return reply({state:row?JSON.parse(row.data):initialWorkspace,revision:row?.revision??0});}catch(e){console.error(e);return reply({error:'Não foi possível carregar seus dados. Tente novamente.'},503)}}
export async function POST(req:Request){const owner=await who();if(!owner)return reply({error:'Entre na prévia privada para salvar suas alterações.'},401);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return reply({error:'Origem inválida.'},403);try{const body=await req.json() as any;if(JSON.stringify(body).length>50000)return reply({error:'Dados muito grandes.'},413);const row=await env.DB!.prepare('SELECT data,revision FROM viva_workspaces WHERE owner=?').bind(owner).first<{data:string;revision:number}>();const state:Workspace=row?JSON.parse(row.data):structuredClone(initialWorkspace);const rev=row?.revision??0;if(body.revision!==rev)return reply({error:'Os dados mudaram em outra aba. Recarregue antes de continuar.'},409);const p=body.payload;
if(body.action==='result'){if(!p.name?.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||!Number.isFinite(p.distance)||p.distance<=0||p.distance>500||!Number.isInteger(p.ms)||p.ms<=0||p.ms>=604800000)return reply({error:'Confira nome, data, distância e tempo.'},400);if(p.link&&!/^https?:\/\//.test(p.link))return reply({error:'Use um link http ou https.'},400);state.results.push({id:crypto.randomUUID(),name:String(p.name).slice(0,150),date:p.date,distance:p.distance,ms:p.ms,source:'Informado pelo atleta',city:String(p.city||'').slice(0,100),link:String(p.link||'').slice(0,1000)});}
else if(body.action==='favorite'){if(!events.some(e=>e.id===p.id))return reply({error:'Evento inválido.'},400);state.favorites=state.favorites.includes(p.id)?state.favorites.filter(i=>i!==p.id):[...state.favorites,p.id];}
else if(body.action==='order'){const e=events.find(e=>e.id===p.eventId);if(!e||!Array.isArray(p.athletes)||p.athletes.length<1||p.athletes.length>10||!['pix','card','installments'].includes(p.payment))return reply({error:'Pedido inválido.'},400);if(p.athletes.some((a:any)=>!a.name?.trim()||!/^\S+@\S+\.\S+$/.test(a.email)||!e.distances.includes(a.distance)||!['PP','P','M','G','GG','XGG'].includes(a.size)||a.size==='XGG'))return reply({error:'Confira os dados dos atletas e o estoque de camisetas.'},400);const ids=[...new Set(p.productIds)] as string[];if(ids.some(i=>!products.some(x=>x.id===i)))return reply({error:'Produto inválido.'},400);let base=0,fee=0;for(const a of p.athletes){const value=racePrice(e,a.distance);base+=value;fee+=feeFor(value,p.payment,state.settings)}const total=base+fee+ids.reduce((s,id)=>s+products.find(x=>x.id===id)!.price,0);state.orders.unshift({id:crypto.randomUUID(),eventId:e.id,athletes:p.athletes.map((a:any)=>({name:String(a.name).slice(0,100),email:String(a.email).slice(0,150),distance:a.distance,size:a.size})),productIds:ids,payment:p.payment,total:Math.round(total*100)/100,fee:Math.round(fee*100)/100,createdAt:new Date().toISOString(),status:'Simulação',delivered:false,shirtDelivered:false,kitDelivered:false,deliveries:p.athletes.map(()=>({shirt:false,kit:false}))});}
else if(body.action==='settings'){for(const key of ['pix','card','installments'])if(!['percent','fixed'].includes(p[key]?.mode)||!Number.isFinite(p[key]?.value)||p[key].value<0||p[key].value>10000)return reply({error:'Taxa inválida.'},400);if(!Number.isInteger(p.maxInstallments)||p.maxInstallments<1||p.maxInstallments>12||p.storeCost<0||p.storeCost>100||p.setup<0||p.rent<0||p.lotQuantity<1)return reply({error:'Confira os valores e parcelas.'},400);state.settings={...state.settings,...p};}
else if(body.action==='invite'){if(!p.name?.trim()||!/^\S+@\S+\.\S+$/.test(p.email)||!['Equipe','Lojista','Organizador'].includes(p.role))return reply({error:'Confira nome e e-mail.'},400);state.invites.push({id:crypto.randomUUID(),name:String(p.name).slice(0,100),email:String(p.email).slice(0,150),role:p.role,createdAt:new Date().toISOString()});}
else if(body.action==='delivery'){const o=state.orders.find(o=>o.id===p.id);if(!o||o.cancelRequested||!['shirtDelivered','kitDelivered','delivered'].includes(p.item))return reply({error:'Pedido indisponível.'},400);if(p.item==='delivered'&&!o.productIds.length)return reply({error:'Este pedido não tem produtos.'},400);if(p.item==='delivered'){if(o.delivered)return reply({error:'Entrega já registrada.'},409);o.delivered=true;o.deliveredAt=new Date().toISOString()}else{if(!Number.isInteger(p.index)||p.index<0||p.index>=o.athletes.length)return reply({error:'Participante inválido.'},400);o.deliveries??=o.athletes.map(()=>({shirt:false,kit:false}));const k=p.item==='shirtDelivered'?'shirt':'kit';if(o.deliveries[p.index][k])return reply({error:'Entrega já registrada.'},409);o.deliveries[p.index][k]=true;}}
else if(body.action==='cancel'){const o=state.orders.find(o=>o.id===p.id);if(!o)return reply({error:'Pedido não encontrado.'},404);o.cancelRequested=true;o.status='Cancelamento solicitado';}
else return reply({error:'Ação desconhecida.'},400);
if(row){const r=await env.DB!.prepare('UPDATE viva_workspaces SET data=?, revision=revision+1 WHERE owner=? AND revision=?').bind(JSON.stringify(state),owner,rev).run();if(!r.meta.changes)return reply({error:'Conflito de atualização. Recarregue.'},409)}else{await env.DB!.prepare('INSERT INTO viva_workspaces (owner,data,revision) VALUES (?,?,1)').bind(owner,JSON.stringify(state)).run()};return reply({state,revision:rev+1});}catch(e){console.error(e);return reply({error:'Não foi possível salvar. Seus dados no formulário foram mantidos.'},503)}}
